"""empty message

Revision ID: 37bc779fcf4c
Revises: e1cddf92bc0b
Create Date: 2026-02-26 21:47:25.303791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37bc779fcf4c'
down_revision = 'e1cddf92bc0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datadetailtransaksi', schema=None) as batch_op:
        batch_op.alter_column('kuantitas',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datadetailtransaksi', schema=None) as batch_op:
        batch_op.alter_column('kuantitas',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
