"""empty message

Revision ID: 564bb77d0f66
Revises: 721799bb2a2a
Create Date: 2026-03-02 20:52:13.393586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564bb77d0f66'
down_revision = '721799bb2a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datariwayatstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaksi_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status_sebelumnya', sa.Text(), nullable=True),
    sa.Column('status_baru', sa.Text(), nullable=False),
    sa.Column('waktu_perubahan', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaksi_id'], ['datatransaksi.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['datauser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datariwayatstatus')
    # ### end Alembic commands ###
