"""empty message

Revision ID: 62f959223875
Revises: 564bb77d0f66
Create Date: 2026-03-03 10:30:20.056267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f959223875'
down_revision = '564bb77d0f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datatransaksi', schema=None) as batch_op:
        batch_op.alter_column('waktu_selesai',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datatransaksi', schema=None) as batch_op:
        batch_op.alter_column('waktu_selesai',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
