"""empty message

Revision ID: 721799bb2a2a
Revises: 37bc779fcf4c
Create Date: 2026-03-02 20:14:24.222340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721799bb2a2a'
down_revision = '37bc779fcf4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datarole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_role')
    )
    op.create_table('datauser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['datarole.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['datauser.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('datauser')
    op.drop_table('datarole')
    # ### end Alembic commands ###
