"""empty message

Revision ID: c679de2c03c5
Revises: 
Create Date: 2026-03-03 23:35:40.719468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c679de2c03c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datapelanggan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_pelanggan', sa.Text(), nullable=False),
    sa.Column('nomor_telepon', sa.Text(), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('catatan_unik', sa.Text(), nullable=True),
    sa.Column('tanggal_input', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataproduk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_produk', sa.Text(), nullable=False),
    sa.Column('kategori', sa.Text(), nullable=True),
    sa.Column('satuan', sa.Text(), nullable=True),
    sa.Column('harga', sa.Integer(), nullable=False),
    sa.Column('waktu_pengerjaan', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datarole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_role')
    )
    op.create_table('datauser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('datatransaksi',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('waktu', sa.Time(), nullable=True),
    sa.Column('diskon', sa.Integer(), nullable=True),
    sa.Column('total_harga_transaksi', sa.Integer(), nullable=False),
    sa.Column('waktu_selesai', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('status_pembayaran', sa.Text(), nullable=True),
    sa.Column('pelanggan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pelanggan_id'], ['datapelanggan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['datarole.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['datauser.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('datadetailtransaksi',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('kuantitas', sa.Float(), nullable=False),
    sa.Column('total_harga_produk', sa.Integer(), nullable=False),
    sa.Column('transaksi_id', sa.String(length=50), nullable=False),
    sa.Column('produk_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produk_id'], ['dataproduk.id'], ),
    sa.ForeignKeyConstraint(['transaksi_id'], ['datatransaksi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datariwayatstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaksi_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status_sebelumnya', sa.Text(), nullable=True),
    sa.Column('status_baru', sa.Text(), nullable=False),
    sa.Column('waktu_perubahan', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaksi_id'], ['datatransaksi.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['datauser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datariwayatstatus')
    op.drop_table('datadetailtransaksi')
    op.drop_table('user_roles')
    op.drop_table('datatransaksi')
    op.drop_table('datauser')
    op.drop_table('datarole')
    op.drop_table('dataproduk')
    op.drop_table('datapelanggan')
    # ### end Alembic commands ###
